-- Core tables
ALTER TABLE department ENABLE ROW LEVEL SECURITY;
ALTER TABLE app_user ENABLE ROW LEVEL SECURITY;
ALTER TABLE document_type ENABLE ROW LEVEL SECURITY;

-- Service and appointment tables
ALTER TABLE service ENABLE ROW LEVEL SECURITY;
ALTER TABLE time_slot ENABLE ROW LEVEL SECURITY;
ALTER TABLE appointment ENABLE ROW LEVEL SECURITY;

-- Communication tables
ALTER TABLE notification ENABLE ROW LEVEL SECURITY;
ALTER TABLE complaint ENABLE ROW LEVEL SECURITY;
ALTER TABLE message ENABLE ROW LEVEL SECURITY;
ALTER TABLE feedback ENABLE ROW LEVEL SECURITY;

-- Document and junction tables
ALTER TABLE officer_department ENABLE ROW LEVEL SECURITY;
ALTER TABLE user_document ENABLE ROW LEVEL SECURITY;
ALTER TABLE required_doc_for_service ENABLE ROW LEVEL SECURITY;
ALTER TABLE appointment_document ENABLE ROW LEVEL SECURITY;
ALTER TABLE user_auth ENABLE ROW LEVEL SECURITY;